### ISSUE TITLE
Please specify license.

### ISSUE THREAD

**Issue by Yukimune** [tucan9389/PoseEstimation-TFLiteSwift#39]
Hi.
Thanks for your awesome work, we refered your postprocess implementation about openpose+TFlite.
When we'd like to use in a production code, we wondering if we can use it.

**Comment by tucan9389** [comment]
@Yukimune 
I added a license file and text on source codes.
You can check the following PR. 

Thank you for your attention.

### Related PR

- https://github.com/tucan9389/PoseEstimation-TFLiteSwift/pull/40

**Comment by Yukimune** [comment]
Thank you so much! we're abel to check codes & license.
