### ISSUE TITLE
.tflite files are missing 

### ISSUE THREAD

**Issue by MeriGarala09** [tucan9389/PoseEstimation-TFLiteSwift#61]
I am trying to run the project in Xcode 11.4.1 but all the .tflite files are missing under **imgclsmob-Pose** folder in Xcode. Anyone, please help me out with this. I want to compile the project.  

Thanks

**Comment by tucan9389** [comment]
@MeriGarala09 

Would you remove the tflite files not existing and compile again?

If you have same issue, please tell me.

**Comment by MeriGarala09** [comment]
<img width="370" alt="Screenshot 2020-08-06 at 5 12 49 PM" src="https://user-images.githubusercontent.com/68893734/89528131-24fb2c00-d808-11ea-99e9-5d46ad3ffb67.png">

@tucan9389 All these files are missing and I have removed all the files. The application is complied now but some .tflite files are using in the code so the app is going crash after the launch.

Please refer the below attachment:
<img width="569" alt="Screenshot 2020-08-06 at 5 16 26 PM" src="https://user-images.githubusercontent.com/68893734/89528439-a357ce00-d808-11ea-9b71-bc0f1de0be75.png">

**Comment by MeriGarala09** [comment]
@tucan9389  Any suggestion???

**Comment by hazel0504** [comment]
Having same issue. I've removed them from build phase, but the app is trying to use them so it crashes.

**Comment by tucan9389** [comment]
https://github.com/tucan9389/PoseEstimation-TFLiteSwift/releases/tag/v1.1.0

In the assets of the release, you can download some models. 
I didn't upload AlphaPose and MobileNet series model yet. You should remove the models, you couldn't get, from the Xcode project.
