### ISSUE TITLE
Connection to assetsd was interrupted - assetsd exited, died, or closed the photo library Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by sgu-fai** [tucan9389/PoseEstimation-TFLiteSwift#62]
hello,

I am getting this error on iPhone8. No apps running on background. I think the msg is clear but any tips to make is work ? maybe load less models ?
```
Connection to assetsd was interrupted - assetsd exited, died, or closed the photo library
Message from debugger: Terminated due to memory issue
```
any idea ?

**Comment by tucan9389** [comment]
Which model did you use?
If you use the big model, you can meet the out of memory issue on old devices.
If you are possible, please use a more small model which is one of the supported models.
