### ISSUE TITLE
reco for body "standing" horizontally (standing not on the feet)

### ISSUE THREAD

**Issue by sgu-fai** [tucan9389/PoseEstimation-TFLiteSwift#63]
Hello, 

I am playing with pose estimation models. I am trying to find a model which run on iOS and able to identify join when the body is horizontal. 
It seems most models (at least poseNet posenet_mobilenet_v1_100_257x257_multi_kpt_strippe) works better vertically.

do you have any suggestions ?

Thank you

**Comment by tucan9389** [comment]
Did you use the apple’s posenet model? In WWDC20, Apple released and introduce the PoseNet model and demo code. I haven't played with it horizontally but it could be a candidate.

**Comment by sgu-fai** [comment]
yeah I got poor result even vertically. Can I contact u offline ?

**Comment by tucan9389** [comment]
How can you contact me offline? I live in South Korea now.

**Comment by sgu-fai** [comment]
I meant by email or ... (outside of github)
