### ISSUE TITLE
LiteBaseline3DPose No such file

### ISSUE THREAD

**Issue by SpencerIO** [tucan9389/PoseEstimation-TFLiteSwift#76]
Hello, I am having trouble finding these files. 

PoseEstimation-TFLiteSwift/PoseEstimation-TFLiteSwift/LiteBaseline3DPose/litebaseline_3dpose_real_S.tflite: No such file or directory

PoseEstimation-TFLiteSwift/PoseEstimation-TFLiteSwift/LiteBaseline3DPose/litebaseline_3dpose_real_L.tflite: No such file or directory

I found the 'imgclsmob-Pose' and the 'Baseline3DPose' tflite files but am still having trouble finding the 'LiteBaseline3DPose' files

Thank you in advance.

**Comment by tucan9389** [comment]
@SpencerIO 
The lite version model is not supported currently. I think you just delete the files on the Xcode project and you can run it.

**Comment by SpencerIO** [comment]
You Are correct good sir. Thank you for responding
