### ISSUE TITLE
can not find the file lightweight_baseline_choi.tflite

### ISSUE THREAD

**Issue by AshishShukla-1992** [tucan9389/PoseEstimation-TFLiteSwift#81]
Hi, I was trying to run your application, but I cant seem to find lightweight_baseline_choi.tflite model file, can you please add the link for downloading.

**Comment by tucan9389** [comment]
please check readme!

**Comment by AshishShukla-1992** [comment]
I have already checked it, the link that is provided there says 404 file not found.

**Comment by tucan9389** [comment]
ops
can tou check this link?

https://github.com/tucan9389/PoseEstimation-TFLiteSwift/releases/download/v2.1.0/lightweight_baseline_choi.tflite
