### ISSUE TITLE
Building project errors

### ISSUE THREAD

**Issue by kirill3333** [tucan9389/PoseEstimation-TFLiteSwift#85]
Hi trying to build this example and found this list of build-time errors
<img width="908" alt="Screenshot 2021-09-19 at 20 16 33" src="https://user-images.githubusercontent.com/1804678/133936685-fcef0a3d-c5f1-4450-b682-be6b036efecf.png">

**Comment by tucan9389** [comment]
Ops, in the new version of TFLiteSwift-Vision, we have to use ‘try’ in the inference line. And maybe in the initialization part, also use try. I’ll fix it later. 

But temporal fixing method before I fix, you can fix the `pod 'TFLitewSwift-Vision'`to `pod 'TFLiteLiteSwift-Vision' '~> 0.2.4'` in Podfile (or `0.2.3`)

**Comment by tucan9389** [comment]
I just fix this issue  #86 
If you have more other error, please reopen this issue and let me know/
