### ISSUE TITLE
Package.swift has no Package.swift manifest for version 0.2.8 

### ISSUE THREAD

**Issue by pc11000** [tucan9389/PoseEstimation-TFLiteSwift#90]
I try to build the project locally but have issues with the TFLiteSwift-Vision dependeny.
I get the error:

`
No such module 'TFLiteSwift_Vision'
`

and

`
/Package.swift has no Package.swift manifest for version 0.2.8 in https://github.com/tucan9389/TFLiteSwift-Vision
`

Using Xcode 13.4.1.

Any ideas what I am doing wrong?

**Comment by tucan9389** [comment]
@pc11000 
Hmm.. did you use Swift Package Manager?

**Comment by pc11000** [comment]
First did with pod install and then i tried directly in Xcode file /add packages...

**Comment by pc11000** [comment]
With pod install I get the output:

`Analyzing dependencies
Downloading dependencies
Installing TFLiteSwift-Vision (0.2.8)
Installing TensorFlowLiteC (2.4.0)
Installing TensorFlowLiteSwift (2.4.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.

[!] Automatically assigning platform `iOS` with version `12.0` on target `PoseEstimation-TFLiteSwift` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `PoseEstimation-TFLiteSwift [Debug]` target overrides the `EXCLUDED_ARCHS[sdk=iphonesimulator*]` build setting defined in `Pods/Target Support Files/Pods-PoseEstimation-TFLiteSwift/Pods-PoseEstimation-TFLiteSwift.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `PoseEstimation-TFLiteSwift [Release]` target overrides the `EXCLUDED_ARCHS[sdk=iphonesimulator*]` build setting defined in `Pods/Target Support Files/Pods-PoseEstimation-TFLiteSwift/Pods-PoseEstimation-TFLiteSwift.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.`

**Comment by tucan9389** [comment]
@pc11000 
I think... you don't need to add packages directly into Xcode. 

You should do following:

1. pod install
2. open `PoseEstimation-TFLiteSwift.xcworkspace`

Can you do it again without the "adding package directly" step?

**Comment by pc11000** [comment]
Also under frameworks the entry is red:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/19648988/180745115-643f14ff-d4f6-4317-bce1-f564c676f8e7.png">

this are the build errors:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/19648988/180745416-8cfdce2c-b2b9-4ba6-b23a-081580c98fbc.png">




> I think... you don't need to add packages directly into Xcode.
> 
> You should do following:
> 
> 1. pod install
> 2. open `PoseEstimation-TFLiteSwift.xcworkspace`
> 
> Can you do it again without the "adding package directly" step?
 ok thx I try

**Comment by tucan9389** [comment]
@pc11000 
I have never seen the error before. 
Right now, I'm a little bit busy. If I solve the problem, I'll update or comment the detail.
If you solve it first, please tell me in this thread. 

Thanks for your error report.

**Comment by pc11000** [comment]
Ok i think now i am a step further. Now I get some errors about missing tflite files:

`
../PoseEstimation-TFLiteSwift/PoseEstimation-TFLiteSwift/imgclsmob-Pose/simplepose_resneta152b_coco.tflite: No such file or directory
`

**Comment by pc11000** [comment]
@tucan9389 I had to download the models manually, now its building and running. Thx for the fast support!
