### ISSUE TITLE
which 3D model is being used?

### ISSUE THREAD

**Issue by SonNguyen2510** [tucan9389/PoseEstimation-TFLiteSwift#92]
Dear author!
Thank you for your work.
I am new to swift code and ios devices.
May I ask you when I build your code, which 3D pose model being used? the basedline3D or the lite one?
And how can I check it?
Thank you so much!

**Comment by tucan9389** [comment]
@SonNguyen2510 

what’s going on the issue 😂 what a open and close multiple times 😂😂

Anyway, as you can see here:

https://github.com/tucan9389/PoseEstimation-TFLiteSwift/blob/58b529a15187b5870f8050e236468ba8ce7619af/PoseEstimation-TFLiteSwift/Live3DRenderingViewController.swift#L38

This repo uses LiteBaseline3DPoseEstimator. You can get the download link on the readme.

**Comment by SonNguyen2510** [comment]
@tucan9389 thank you so much for the fast respond.
I open an issue by mistake then close it, sorry 😅😅

**Comment by SonNguyen2510** [comment]
Btw, I see that everytime I build the project, it automatically download all the models again, how can I turn it off? Can I use my own model instead of the downloaded model? thank you for your time again

**Comment by tucan9389** [comment]
Once you empty this file(don't delete it), it'll work like turning off download.

https://github.com/tucan9389/PoseEstimation-TFLiteSwift/blob/master/RunScripts/tflite_models.csv

**Comment by SonNguyen2510** [comment]
I see, thank you :)
