### ISSUE TITLE
Baseline3DPoseEstimator returns only 14 points, not 18 points.

### ISSUE THREAD

**Issue by TaichiAkimoto** [tucan9389/PoseEstimation-TFLiteSwift#94]
I have cloned this repo and tried 3D pose estimation using Baseline3DPoseEstimator, not LightBaseline3DPoseEstimator.
I have noticed that only 14 points are displayed on the screen. I mean from Pelvis to L_Wrist. As a result, right half of the human body is not drawn on the screen, while they are drawn on gifs on the REAME, and they are defined in types on the code.
I just thought this is dues to vagueness of bitmaps I input to the model, but whatever images I give to the model, it returns 14 points, which I have verified using print function.
I have read through softArgmax3D function, but I don't understand mathematical intricacies of the function, so it might be the problem.
Does anyone know how to solve this problem?

**Comment by tucan9389** [comment]
@TaichiAkimoto 
do you have any screenshot?

**Comment by TaichiAkimoto** [comment]
@tucan9389 
After reading Swift code thoroughly, I have found that HumanKeypoints class was handling human body with 14 points. So, by replacing `LiteBaseline3DPoseEstimator` with `Baseline3DPoseEstimator` in HumanKeypoints class, I could see right half of human body just as expected with 14 points. I should have read code more carefully before submitting an issue.
